function cCudaDeviceWait

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA61_GeneralSgl_v11f', ...
    '-output','CudaDeviceWait61', ...
    'CudaDeviceWait.cpp');

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA75_GeneralSgl_v11f', ...
    '-output','CudaDeviceWait75', ...
    'CudaDeviceWait.cpp');
 
 