function cFourierTransformShiftSingleGpu

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA61_FourierTransformShift_v11a', ...
%     '-output','FourierTransformShiftSingleGpu61', ...
%     'FourierTransformShiftSingleGpu.cpp');
% 
% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA75_FourierTransformShift_v11a', ...
%     '-output','FourierTransformShiftSingleGpu75', ...
%     'FourierTransformShiftSingleGpu.cpp');

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA86_FourierTransformShift_v11a', ...
    '-output','FourierTransformShiftSingleGpu86', ...
    'FourierTransformShiftSingleGpu.cpp');


