function cExecuteInverseFourierTransformSingleGpu

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart','-lcufft', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA61_FourierTransform_v11a', ...
%     '-lCUDA61_ScaleComplexMatrix_v11a', ...
%     '-output','ExecuteInverseFourierTransformSingleGpu61', ...
%     'ExecuteInverseFourierTransformSingleGpu.cpp');
% 
% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart','-lcufft', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA75_FourierTransform_v11a', ...
%     '-lCUDA75_ScaleComplexMatrix_v11a', ...
%     '-output','ExecuteInverseFourierTransformSingleGpu75', ...
%     'ExecuteInverseFourierTransformSingleGpu.cpp');

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA86_FourierTransform_v11a', ...
    '-lCUDA86_ScaleComplexMatrix_v11a', ...
    '-output','ExecuteInverseFourierTransformSingleGpu86', ...
    'ExecuteInverseFourierTransformSingleGpu.cpp');

