function cConjugateComplexMatrixSingleGpu

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA61_ConjugateComplexMatrix_v11a', ...
    '-output','ConjugateComplexMatrixSingleGpu61', ...
    'ConjugateComplexMatrixSingleGpu.cpp');

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA75_ConjugateComplexMatrix_v11a', ...
    '-output','ConjugateComplexMatrixSingleGpu75', ...
    'ConjugateComplexMatrixSingleGpu.cpp');
