function cScaleComplexMatrixSingleGpu

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA61_ScaleComplexMatrix_v11a', ...
    '-output','ScaleComplexMatrixSingleGpu61', ...
    'ScaleComplexMatrixSingleGpu.cpp');

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA75_ScaleComplexMatrix_v11a', ...
    '-output','ScaleComplexMatrixSingleGpu75', ...
    'ScaleComplexMatrixSingleGpu.cpp');

