function cMultiplyAccumComplexMatrixComplexMatrixSingleGpu

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart','-lcufft', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA61_MultiplyAccumMatrixComplexComplex_v11a', ...
%     '-output','MultiplyAccumComplexMatrixComplexMatrixSingleGpu61', ...
%     'MultiplyAccumComplexMatrixComplexMatrixSingleGpu.cpp');
% 
% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart','-lcufft', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA75_MultiplyAccumMatrixComplexComplex_v11a', ...
%     '-output','MultiplyAccumComplexMatrixComplexMatrixSingleGpu75', ...
%     'MultiplyAccumComplexMatrixComplexMatrixSingleGpu.cpp');

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA86_MultiplyAccumMatrixComplexComplex_v11a', ...
    '-output','MultiplyAccumComplexMatrixComplexMatrixSingleGpu86', ...
    'MultiplyAccumComplexMatrixComplexMatrixSingleGpu.cpp');