function cMultiplyComplexMatrixComplexMatrixSingleGpu

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart','-lcufft', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA61_MultiplyMatrixComplexComplex_v11a', ...
%     '-output','MultiplyComplexMatrixComplexMatrixSingleGpu61', ...
%     'MultiplyComplexMatrixComplexMatrixSingleGpu.cpp');
% 
% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart','-lcufft', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA75_MultiplyMatrixComplexComplex_v11a', ...
%     '-output','MultiplyComplexMatrixComplexMatrixSingleGpu75', ...
%     'MultiplyComplexMatrixComplexMatrixSingleGpu.cpp');

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA86_MultiplyMatrixComplexComplex_v11a', ...
    '-output','MultiplyComplexMatrixComplexMatrixSingleGpu86', ...
    'MultiplyComplexMatrixComplexMatrixSingleGpu.cpp');
