function cTestKernelInGpuMem

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA_GeneralSgl_v1d', ...
%     'TestKernelInGpuMem.cpp');
 
 mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA86_GeneralSgl_v11f', ...
    '-output','TestKernelInGpuMem86', ...
    'TestKernelInGpuMem.cpp');