function cExecuteFourierTransformSingleGpu

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart','-lcufft', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA61_FourierTransform_v11a', ...
%     '-output','ExecuteFourierTransformSingleGpu61', ...
%     'ExecuteFourierTransformSingleGpu.cpp');
% 
% mex('-R2018a',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart','-lcufft', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA75_FourierTransform_v11a', ...
%     '-output','ExecuteFourierTransformSingleGpu75', ...
%     'ExecuteFourierTransformSingleGpu.cpp');

mex('-R2018a',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA86_FourierTransform_v11a', ...
    '-output','ExecuteFourierTransformSingleGpu86', ...
    'ExecuteFourierTransformSingleGpu.cpp');


